### ISSUE TITLE
EbookLib

### ISSUE THREAD

**Issue by stvnliu** [Ate329/KindleRSS#4]
See https://pypi.org/project/EbookLib/ for an EPUB manipulation and modification library to integrate into the program

**Comment by Ate329** [comment]
OK

**Comment by stvnliu** [comment]
So I tried to do that and generate an EPUB file with the contents, but it kept giving me `link.etree.ParseError: Document is empty`

**Comment by stvnliu** [comment]
Project is using ebooklib epub functions. This issue has been resolved.
